## This allows Github actions to build this project
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: Staging augmenter
        run: |
          wget https://github.com/xstefank/staging-augmenter/raw/main/staging-augmenter
          chmod +x staging-augmenter
          ./staging-augmenter
          ls ~/.m2/settings.xml

      - name: build with maven
        run: mvn -B verify javadoc:javadoc --file pom.xml
